set -g mouse on

setw -g mode-keys vi

# Enable Tmux to forward OSC 52 sequences to Ghostty
set -s set-clipboard on

# Allow applications inside tmux (like Neovim) to bypass Tmux filters
set -g allow-passthrough on

# change prefix
unbind C-b
set-option -g prefix C-a
bind-key C-a send-prefix

# change index to start with 1
set -g base-index 1
set -g pane-base-index 1

# change color
set -g status-style bg=#00ffff,fg=#000000
set -g window-status-style fg=#000000

set -g pane-border-style fg=default
set -g pane-active-border-style fg=#00ffff

set -g message-style bg=#00ffff,fg=#000000
set -g window-status-current-style bg=#00ffff,fg=#000000
