timeout: 5
wallpaper: boot():/bg.jpg
term_font_scale: 3x3
interface_branding: Welcome back
interface_branding_color: 88ccff
interface_help_colour: 1f2c82
interface_help_hidden: yes

# Fully transparent background (TTRRGGBB)
term_background: ff000000
term_margin_top: 400
term_margin_bottom: 200

term_palette: 2e3440;ffb8d1;66ccff;cba6f7;89b4fa;f5c2e7;94e2d5;bac2de
term_palette_bright: 4c566a;ffc4d9;66ccff;d2b3ff;a4c5fa;ffcceb;9fedfc;ffffff

/Arch Linux
    protocol: linux
    kernel_path: boot():/vmlinuz-linux
    module_path: boot():/initramfs-linux.img
    cmdline: root=UUID=786b85d1-ef72-424a-8b44-5ac02fe58123 rw rootfstype=ext4

/Windows
    protocol: efi_chainload
    image_path: guid(fe73de5d-ee64-497b-9521-073fd2265ada):/EFI/Microsoft/Boot/bootmgfw.efi
